### ISSUE TITLE
Edit caption on the PhotoBrowser

### ISSUE THREAD

**Issue by heshan-nibaya** [nolimits4web/Framework7#1101] opened 2016-08-24 13:09 UTC
- [x] bug
- [x] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: v1.4.2
- Platform and Target: CORDOVA, ANDROID,
### What you did

We were trying to setup the PhotoBrowser so it can be used to edit the caption as well, Similar to what you find in WhatsApp or Viber when sending an image.

Below is the captionTemplate we used

```
<div class="photo-browser-caption" data-caption-index="{{@index}}">
    <input type="text" value="{{caption}}">
</div>
```
### Expected Behavior

Expected was to edit the caption when we tap on the input box using the keyboard.
### Actual Behavior

Although the template works well, but the android keyboard is not displayed.

**Comment by valnub** [comment] 2016-10-07 20:27
Hi, can you give some more additional information like this please?

- Does this issue occur only on Android or on iOS as well?
- Which Android version did you use?
- What device are you using? (Manufacturer and model, e.g. Samasung Galaxy S7)
- Which Cordova version are you using?
- Does this problem occur in the browser as well or only in Cordova?

Thanks :)

**Comment by heshan-nibaya** [comment] 2016-10-10 02:45
hi @valnub sure i'll get that information for you...

**Comment by heshan-nibaya** [comment] 2016-10-10 05:53
hi @valnub hope this helps...

- Does this issue occur only on Android or on iOS as well?
Happens on both Platforms (We only used the iOS template didn't try Material template)

- Which Android version did you use?
KitKat(v4.4.2)

- What device are you using? (Manufacturer and model, e.g. Samasung Galaxy S7)
Android:Huawei Honor Holly
iOS: iphone 6(v8.3)

- Which Cordova version are you using?
5.3.1

- Does this problem occur in the browser as well or only in Cordova?
We did not test it in browser.

**Comment by valnub** [comment] 2016-10-11 21:28
Can you test your code in a browser? Then we know if it is a Cordova problem or F7 problem and if we need to fix it.

**Comment by valnub** [comment] 2016-10-11 21:30
If possible, a minimal stripped-down version as fiddle or codepen would be the best. You can use these templates for that:

- iOS [JSFiddle](https://jsfiddle.net/mvs820k0/)/[Codepen](https://codepen.io/nolimits4web/pen/vXmmgG)
- Material [JSFiddle](https://jsfiddle.net/u8a87yd2/2/)/[Codepen](https://codepen.io/nolimits4web/pen/pEPPPK)

Then we can exactly see what's going on.

Oh, and is there a specific reason why you're using iOS templates on an Android device? :-) I'm not sure if F7 supports this..

**Comment by ZanderBrown** [comment] 2016-10-11 21:37
As it's all standard js, css & html why wouldn't the  iOS theme work on Android.

**Comment by heshan-nibaya** [comment] 2016-10-13 05:32
well we started on this project before the material theme... later we updated the theme to newer version and since the iOS implementations worked.. we kept the iOS theme.

I'm not sure if this is possible to be tested on web browser because.. it is something to do with mobile keyboard is not displayed when tapping on the input html control. (Something to do with events, transitions or css itself maybe? or it can be a cordova issue)

Everything else in F7 works fine, even the **`captionTemplate`**  in PhotoBrowser when we used the following template (with the exception of tapping on the input textbox)

```
<div class="photo-browser-caption" data-caption-index="{{@index}}">
    <input type="text" value="{{caption}}">
</div>
```

**Comment by oudoken** [comment] 2017-02-27 15:12
Hi there,
I can confirm also the problem. If lazyLoading is enabled the image are loaded and visible correctly when tapping the NEXT image (or sliding right) if sliding back the problem is here again (no lazy because the image it's already there).
Also double tap or pinch/punch make the full image visible.
Some sort of visual glitch...

**Comment by ZanderBrown** [comment] 2017-03-01 17:33
There hasn't been a response by the issues owner in 20 days.
This issue **will be closed in 7 days** if no further response is submitted

**Comment by heshan-nibaya** [comment] 2017-03-03 13:46
Hi actually our requirement changed, so we moved on from this implementation. Sorry for not informing it earlier. Anyway I'm not exactly sure what happened, but it would be nice to have editable caption method in the future.

**Comment by ZanderBrown** [comment] 2017-03-03 15:39
@heshan-nibaya noted in our internal todo list.

**Closed by ZanderBrown** 2017-03-03 15:39 UTC
Labels: Android bug, Native App, Need Details
