### ISSUE TITLE
Page Slider

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#564] opened 2015-08-02 15:29 UTC
Can we have Page Slider something like this - 

![image](https://cloud.githubusercontent.com/assets/7137859/9026752/3575514e-3959-11e5-8845-12a7e1ad45bf.png)

I.e. I am looking for swipe on tabs.

**Comment by murliatdure** [comment] 2015-08-02 15:31
![image](https://cloud.githubusercontent.com/assets/7137859/9026756/81944134-3959-11e5-8595-ae12ba54eff0.png)

http://www.thelastbug.es/android/sliding-tabs-material-design/

**Comment by nolimits4web** [comment] 2015-08-02 16:00
There is a Swiper for that. Duplicate of #542

**Closed by nolimits4web** 2015-08-02 16:00 UTC

**Comment by murliatdure** [comment] 2015-08-05 03:54
I guess - the methods are deprecated in current release?

![image](https://cloud.githubusercontent.com/assets/7137859/9078042/ab52528a-3b53-11e5-8e2d-b9316b6360be.png)

**Comment by nolimits4web** [comment] 2015-08-06 19:04
No, they not deprectated
