### ISSUE TITLE
Navbar drops shadow over searchbar

### ISSUE THREAD

**Issue by waptaxi** [nolimits4web/Framework7#1437] opened 2017-03-21 13:24 UTC
Navbar shadow added in 1.5.4 drops shadow over the searchbar as you can see in Search Bar example in kitchen sink.

**Comment by J05HI** [comment] 2017-03-22 12:07
@waptaxi 
I can confirm. The added shadow it soo much.

**Comment by waptaxi** [comment] 2017-03-22 14:00
Also, now we have shadow for searchbar, but there is no "no-shadow" class for searchbar and subnavbar.

**Comment by macdonst** [comment] 2017-03-22 15:28
@waptaxi how do you reproduce this? When I look at the Kitchen Sink example in Chrome I don't see that behaviour.

<img width="264" alt="screenshot 2017-03-22 08 28 28" src="https://cloud.githubusercontent.com/assets/353180/24205769/90812534-0ed9-11e7-9f00-c94361ec1ede.png">

**Comment by ZanderBrown** [comment] 2017-03-22 15:50
![image](https://cloud.githubusercontent.com/assets/17074021/24206791/37bacd9a-0f17-11e7-80f6-022abc7a5d20.png)

**Comment by macdonst** [comment] 2017-03-22 21:37
@ZanderBrown right, I believe that there is a bug but I'm trying to figure out a reproduction scenario to see if I can help. I've pulled the latest down from master and can't reproduce on Chrome or Safari.

**Comment by ZanderBrown** [comment] 2017-03-22 22:20
Guess @nolimits4web fixed it in master already

**Comment by nolimits4web** [comment] 2017-03-24 09:45
@ZanderBrown yes, it is already fixed in Master

**Closed by nolimits4web** 2017-03-24 09:45 UTC
Labels: Bug confirmed, Material Theme
