### ISSUE TITLE
Status bar overlay does not work on iOS 9

### ISSUE THREAD

**Issue by jose-carrillo** [nolimits4web/Framework7#531] opened 2015-07-05 03:34 UTC
Adding the div with class with-statusbar-overlay does not work in iOS 9.

http://www.idangero.us/framework7/docs/status-bar.html

![img_0919](https://cloud.githubusercontent.com/assets/174578/8510212/281f6036-22a5-11e5-872d-ebeeb886f073.PNG)

**Comment by nolimits4web** [comment] 2015-07-05 16:43
I think it is too early to talk about iOS9 as it is still in early better. But i guess it is iOS bug. There is no specific about it in F7

**Comment by jose-carrillo** [comment] 2015-07-05 19:23
I just wanted to make you aware. Like you said, it is perhaps too early but I don't think it is a bug. I have other standalone work that does not behave the same way. If you save this link http://www.demos.ultimatezencart.com/0701M/ to the home screen, you'll see that it isn't affected. I do have other work with jQuery Mobile that it is affected so, like you say, it is too early.

Thanks by the way for such an awesome framework. I have worked with several mobile and responsive frameworks and framework7 is by far the best I've seen.

**Comment by johnjamesjacoby** [comment] 2015-08-03 19:28
iOS 9 beta 4 still exhibits this issue. I haven't looked into it yet at all to offer a solution.

**Comment by johnjamesjacoby** [comment] 2015-08-25 17:20
Bea 5 also is still broken.

Issue in the Apple developer forums: https://forums.developer.apple.com/message/30098#30098

**Comment by nolimits4web** [comment] 2015-08-26 19:17
@johnjamesjacoby yes, it is definitely iOS issue, nothing can do with that at the moment. Hope this will be fixed to final release

**Comment by johnjamesjacoby** [comment] 2015-09-10 13:31
Still broken in iOS 9 GM Seed.

**Comment by burntool** [comment] 2015-09-18 06:47
I fear this is intended. Read about in some other place yesterday. Though I can't figure out the reasoning behind it.

**Comment by ihenk** [comment] 2015-09-18 08:09
Steps to Reproduce:
1. Create new project in Xcode 7
2. Set UIViewControllerBasedStatusBarAppearance to "false" in Info.plist
everything will be ok.

**Comment by RandomGenius** [comment] 2015-09-19 18:13
@ihenk No, Framework7 is intended for pure web apps that don't use Xcode nor the iOS SDK at all. They use a meta tag to be able to be added to the homescreen as a fullscreen web app.

**Comment by nolimits4web** [comment] 2015-09-20 10:58
@RandomGenius 
> Framework7 is intended for pure web apps that don't use Xcode nor the iOS SDK at all

Nope, Framework7 is intended to be used as a Cordova/Phonegap app, pure web app is not a 100% F7's target.

**Comment by nolimits4web** [comment] 2015-09-20 10:59
Guys, i am closing this issue as it is iOS issue, it just doesn't open webapp in fullscreen. Cordova apps works fine with status bar overlay

**Closed by nolimits4web** 2015-09-20 10:59 UTC

**Comment by Nicolapps** [comment] 2015-12-11 18:31
It's fixed in iOS 9.2 !

**Comment by nolimits4web** [comment] 2015-12-11 18:32
Seriously? Nice :D

**Comment by momomo** [comment] 2016-04-19 07:45
No it's not.
