### ISSUE TITLE
Material : Tabs changing on scroll left or right

### ISSUE THREAD

**Issue by Adri-7** [nolimits4web/Framework7#725] opened 2015-11-23 21:02 UTC
It would be cool if we could have scrolling tabs with Framework7 just like in most of the android applications.

**Comment by Adri-7** [comment] 2015-11-23 21:03
It would be cool if we could have scrolling tabs with Framework7 just like in most of the android applications.

**Comment by nolimits4web** [comment] 2015-11-25 11:43
There is a Swiper for that. Duplicate of #542

**Comment by Adri-7** [comment] 2015-11-25 11:47
Ok thanks, I didn't see that before.

**Closed** 2015-11-26 12:37 UTC
