### ISSUE TITLE
Zoom problems in photo browser in android

### ISSUE THREAD

**Issue by shaulhadar** [nolimits4web/Framework7#539] opened 2015-07-13 16:47 UTC
Hi Vlad, I found a bug in the photo browser in Android. when clicking twice and zooming in, I can't click twice to zoom out, it is stuck on the zoomed picture....

thanks for your time,

shaul.

**Comment by nolimits4web** [comment] 2015-07-18 19:38
Hi, will check it, thanks

**Comment by nolimits4web** [comment] 2015-07-18 19:41
And what is Android version and browser? As i can't replicate this issue

**Comment by shaulhadar** [comment] 2015-07-19 04:51
hi vlad, i used android lollipop...
i also exported to crosswalk 14 if it helps...

i checked and saw that it is supposed to work, i dont know why it didnt work for me, maybe its connected to crosswalk?

**Comment by shaulhadar** [comment] 2015-07-19 08:10
OK, I checked again and it still doesn't work even when I check the kitchen sink online demo as well. I am working with latest Chrome on Android 5 lollipop.

**Comment by nolimits4web** [comment] 2015-07-25 11:44
Still work for me. Try on another device. It could be device-related issue

**Comment by nolimits4web** [comment] 2015-11-08 14:01
Closing as duplicate of #671

**Closed by nolimits4web** 2015-11-08 14:01 UTC
